#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink:        /:categories/:year/:month/:title/

microblog:
  username:       lildude
  site:           dev
  
 # Defaults for the entire site
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: ""
