#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

 # Defaults for the entire site
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title: ""